# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28e6c0ea879dc4c2de2a35af27a4dc6b29262854bb16cb06143148ba90388d9e4a500f643fa59363a098f5d7c3a5e980bd545109992f7f2c7e85a1efda78b0b

test:
  secret_key_base: 60ba3473dbe162e8035d32a93b0554533c03360d7aa7f03a673213ca81a3dd01a5545a22f7192f9756b9984e9bf17954f6c0adeb866d785d939b6bdff2d08653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
